stages:
  - test
  - deploy

# Étape 1 : Tester ton code HTML, CSS et JS
validate_site:
  stage: test
  image: node:20
  before_script:
    # Installation globale des outils
    - npm install -g htmlhint stylelint eslint stylelint-config-standard
  script:
    # Vérification HTML
    - htmlhint ./*.html
    # Vérification et correction automatique CSS
    - npx stylelint "**/*.css" --config .stylelintrc.json --fix || true
    # Vérification JS (avec config ESLint)
    - npx eslint "**/*.js" --config .eslintrc.cjs --max-warnings=0
  only:
    - main
